### PR TITLE
Remove jupyterhub publish service

### PR DESCRIPTION
**Pull request by maulikjs**
## Related Issues and Dependencies
https://issues.redhat.com/browse/ODH-405 

## This Pull Request implements
This MR deprecates the Jupyterhub Publish service which was deprecated downstream

### CODE REVIEW

**Comment by vpavlin** [comment]
@maulikjs You are changing teh Pipfile, so you need to re-lock the deps (that's probably why the CI is failing)

**Comment by crobby** [comment]
Deprecate or remove?

**Comment by maulikjs** [comment]
>Deprecate or remove?

is there a difference? 🤔

**Comment by crobby** [comment]
> > Deprecate or remove?
> 
> is there a difference?

Deprecate means we're leaving it alone for now, but will remove in the future.  Remove means....remove :)

**Comment by maulikjs** [comment]
@vpavlin can you check now?

**Comment by VaishnaviHire** [comment]
@maulikjs @vpavlin Tested the updated PR. No longer getting error due to `Pipfile.lock` file.

However the build failed with following error:

```
Successfully pushed image-registry.openshift-image-registry.svc:5000/opendatahub/jupyterhub-img:latest
Warning: Push failed, retrying in 5s ...
Registry server Address: 
Registry server User Name: serviceaccount
Registry server Email: serviceaccount@example.org
Registry server Password: <<non-empty>>
error: build error: Failed to push image: error copying layers and metadata from "containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.imagestore=/var/lib/shared]image-registry.openshift-image-registry.svc:5000/opendatahub/jupyterhub-img:latest" to "docker://image-registry.openshift-image-registry.svc:5000/opendatahub/jupyterhub-img:latest": Error writing blob: Error initiating layer upload to /v2/opendatahub/jupyterhub-img/blobs/uploads/ in image-registry.openshift-image-registry.svc:5000: received unexpected HTTP status: 500 Internal Server Error
```

**Comment by VaishnaviHire** [comment]
lgtm

I think the issue mentioned above was specific to my test cluster. Successfully tested the updated image on new cluster.

**Review by VaishnaviHire — APPROVED** [review]

**Comment by vpavlin** [comment]
@maulikjs Looks good..can you please rebase thought? We just merged another PR and there are conflicts..sorry about it

**Comment by vpavlin** [comment]
lgtm

**Pull request merged**
