### PR TITLE
Update JSP to 0.6.3

### PR DESCRIPTION
**Pull request by vpavlin**
## Related Issues and Dependencies

…

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

… Explain your changes.

### CODE REVIEW

**Comment by vpavlin** [comment]
The built image is available here:

quay.io/odh-jupyterhub/jupyterhub-img:pr-117

**Review by lucferbux — APPROVED** [review]

**Review by anishasthana — APPROVED** [review]
I replaced the JupyterHub image in a RHODS deployment with the one from this PR. Things seem to be deployed correctly -- I was able to spin up a new notebook.

**Comment by lucferbux** [comment]
Yeah, as @anishasthana said i replaced this image in a cluster and so far the Jupyter HA works great.

**Pull request merged**
