### PR TITLE
Custom namespace support

### PR DESCRIPTION
**Pull request by anishasthana**
This PR will allow us to deploy Juypterhub notebooks to a different namespace than the main server

CC @rimolive

### CODE REVIEW

**Comment by anishasthana** [comment]
For testing purposes you can pass the following parameter to the JupyterHub container.

```
            - name: NOTEBOOK_NAMESPACE
              value: rhods-notebooks
```

**Comment by crobby** [comment]
I've tested the resultant image from this change.  With the extra permissions, things seemed to work nicely.

**Comment by rimolive** [comment]
In addition to what @anishasthana said, the thing is that Random UID assignment on pods is an OpenShift thing, thus the KubeSpawner class from jupyterhub doesn't implement it. Meaning that the UID added in the image Dockerfile will always be used, no matter how many pods Jupyterhub will spawn. The `nonroot` SCC could give the JH spawner permission to assign their fixed UID, but not root. That's the only relaxed rule compared to `restricted` SCC (used by default).

One other option would be, since we created the OpenShiftSpawner class for Jupyterhub, implement that same Random UID assignment from OpenShift. However, I believe both will be disconnected implementations and we can face scenarios where the Openshift cluster was deployed with a custom UID range and JH will not sync up these settings.

Having that said, I believe the best practical solution would be use the `nonroot` SCC.

**Comment by vpavlin** [comment]
To sum up the latest changes - we figured the problem with SCC errors is that KubeSpawner sets UID to the one of user in the JH container. As each namespace comes with a different range of allowed UIDs, the cross-namespace deployment failed. We just need to make sure the UID is NOT set (i.e. == None) to allow OpenShift generate it correctly.

**Comment by vpavlin** [comment]
lgtm

**Pull request merged**
